POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email" : "test00@gmail.com",
  "password" : "1234"
}

###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
"email" : "test01@gmail.com",
"password" : "1234"
}

###
POST http://localhost:8080/api/auth
Content-Type: application/json

{
  "email" : "test02@gmail.com",
  "password" : "1234"
}